version: "3.8"
services:
  web:
    build: .
    container_name: vink-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - GOOGLE_PLACE_ID=${GOOGLE_PLACE_ID}
      - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
      - NEXT_PUBLIC_SANITY_API_VERSION=${NEXT_PUBLIC_SANITY_API_VERSION}
